name: Firestore rules

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'database/firestore.rules'
  push:
    branches:
      - develop
    paths:
      - 'database/firestore.rules'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: '10'
      - run: npm ci
      - run: npm run ci:test:rules
      - if: ${{ github.event_name == 'push' && success() }}
        run: npm run deploy:rules
